### PR TITLE
Add Groq API support and integration

### PR DESCRIPTION
**Pull request by icarecti**
Introduced the Groq API integration into the existing service. Made changes to necessary files to include Groq types, models and updated error handling. Now, users can get Groq service access by adding GROQ_API_KEY to the environment configuration file.

### CODE REVIEW

**Comment by icarecti** [comment]
To test this PR you need an Groq API key. You can get one for free here: https://console.groq.com/playground

**Comment by ymetz** [comment]
Thanks for the great contribution! I will check it, and add an option to enter the groq api key in the frontend. 

Also it seems that we need to find a better solution in smartgpt.ts to replace the if-statements, this will become messy, in particular if we add even more providers like Google Gemini (which is planned in the near future).
I could imagine an easier solution with a mapping of types, maybe similar to:

```
  const availableStreams = {
   'openai': OpenAIStream, 
   'claude: AnthropicStream,
   'groq': GroqStream
  }

  const stream = await availableStreams[modelName](model, initialSystemPrompt, temperatureToUse, openAIkey, await messages, undefined);
```

If you find the time to look at this, it would be amazing.
Also, please try to check if 'npm build' runs through before commiting. Thanks already :)

**Comment by icarecti** [comment]
The PR works but still has some rough edged, let me do some fine-tuning before you merge it into main.

**Comment by icarecti** [comment]
Now after the refactoring most of the changes are in teh streamFactory when a new provider is added and the change will be reflected in chat and smartgpt. All providers that follow the openAI API are very easy to add. For providers that dont follow the openAI API also the parsing of the response has to be modified within the streamFactory.

I moved the api-keys into the settings modal to have more space for many more keys.

Due to missing unit tests I am not fully sure if the previous behaviour is still exactly the same but I did a handful of manual tests and it looked  fine.

**Comment by ymetz** [comment]
Thank you again for the awesome contribution! I really like your solutions with the stream factory and the keys. I renamed "Settings" to "API Keys & Settings", that should avoid any confusion.

I still got a faulty output for SmartGPT, when using a Groq model as a resolver or researcher (due to getProvider not working correctly), but i think i fixed this. I integrated all your changes (among others, and including my hotfix) in a new branch (https://github.com/ymetz/smartgpt_ui/tree/we_need_more_speed--adding-groq). If you like, you can have a final look. If you have no objections, i will merge it into main later. Thanks a lot!

**Comment by icarecti** [comment]
thanks for the fix. You can merge it.

I saw that in the home.tsx the handling of the defaultModelId is not yet correct. I can have a look into that once the other branch is merged into main.
The worst that can happen in the current form is that you only set the Groq-key. Opening a new chat the default model still is gpt-3.5. You then have to go to the settings in the header and toggle back to a groq model.

**Pull request closed without merging**
